Uniform use of job
zonemaster/zonemaster-backend pull request #1090
Opened 2023-03-13 13:24 UTC by pnax

## Purpose

The API has been updated with new methods `job_*` (#1054, #1083) . A _test_ can now be referred as a _job_. It would then make sense to rename `test_id` to `job_id`. This PR does that for the new API methods.

## Context

#1084 

## Changes

* documentation (API.md)
* tests (t/test01.t and t/lifecycle.t)
* implementation (RPCAPI.pm, DB.pm, SQLite.pm, MySQL.pm, PostgreSQL.pm)
* deprecate (planned removal v2024.1) `test_id` API documentation

## How to test this PR

Unit tests should pass.

2023-03-14 09:52 UTC, matsduf commented
What is a "job" and what is a "test"? I think it is unclear in the API document. It starts by saying "Health checks are called tests in Zonemaster lingo" so what we store in the database are those "test results" or "job results"? The job is there to run a test and that would result in a "test result". If so, "test-id" is more reasonable than "job-id". The test remains when the job has completed.

I think this should be clarified in the API document.

2023-03-14 09:52 UTC, matsduf requested changes
What is a "job" and what is a "test"? I think it is unclear in the API document. It starts by saying "Health checks are called tests in Zonemaster lingo" so what we store in the database are those "test results" or "job results"? The job is there to run a test and that would result in a "test result". If so, "test-id" is more reasonable than "job-id". The test remains when the job has completed.

I think this should be clarified in the API document.

2023-03-14 12:52 UTC, pnax commented
> What is a "job" and what is a "test"?

The way I see it, a job runs some tests. The tests are the one from the specification.

2023-04-17 10:25 UTC, matsduf commented
I looked through the API document, and I do not think that "job result" is a good term. A job is run and a test result comes out. If we communicate that it is a Job Result, then it is less understandable than Test Result. But it is fine to say that a job has been created.

If you look for a test result, what should the identifier be? "Test ID" or "Job ID"? Here I think Test ID is probably easier to understand, but Job ID will work.

If the outcome of a Job is a Test Result, then the method should rather be `job_outcome` or `test_result` than `job_results`.

When the user runs (orders) a domain test, a Job is created and then there will be Test Result to present to the user.

2023-09-27 10:49 UTC, closed without merging

2023-09-27 10:49 UTC, pnax commented
Closing this PR. The renaming might happen once the new RPCAPI is stabilized.