Refactor profiles
zonemaster/zonemaster-backend pull request #802
Opened 2021-06-22 18:07 UTC by mattias-p

## Purpose

This PR is mainly a refactoring in preparation for implementing the validation of the PUBLIC PROFILES and PRIVATE PROFILES sections, but it also includes some improvements to error handling.

## Context

This PR is a step towards #685.

## Changes

A weird behavior is fixed. Normally when you specify a non-existing path for a profile, zm-testagent refuses to start. But if the name of the profile is "default", zm-testagent starts anyway and the default profile is used instead of the non-existent one. After this PR zm-testagent will refuse to start if a profile path does not exist - no matter what name the profile has.

Error messages from two sources are updated with more context. In one case the path of the offending profile file is included, and in the other case both the name of the profile and its path is included in the error message.

Some work (merging of profile objects) is moved from being done once per test item into being done once at startup.

In terms of refactorings, some private data representations are simplified, some variables are rename, some formatting is updated.

## How to test this PR

1. Update the PUBLIC PROFILES section in your backend_config.ini:
    ```
    [PUBLIC PROFILES]
    default = /non-existent
    ```
    Restart zm-testagent and make sure that it refuses to come up. Also make sure that a log entry is written containing details of the error.

2. Update the PUBLIC PROFILES section in your backend_config.ini:
    ```
    [PUBLIC PROFILES]
    default = /etc/shadow
    ```
    Restart zm-testagent and make sure that it refuses to come up. Also make sure that a log entry is written containing details of the error.

3. Update the PUBLIC PROFILES section in your backend_config.ini:
    ```
    [PUBLIC PROFILES]
    default = /bin/false
    ```
    Restart zm-testagent and make sure that it refuses to come up. Also make sure that a log entry is written containing details of the error.

4. Update the PUBLIC PROFILES section in your backend_config.ini:
    ```
    [PUBLIC PROFILES]
    default = /tmp/empty.profile
    ```
    Run `echo {} > /tmp/empty.profile`.
    Restart zm-testagent and make sure that you are able to complete a test with it.

2021-07-02 15:53 UTC, matsduf requested changes
It does not work to have a private profile.

Scenario 1:
```
[PUBLIC PROFILES]
default-no-ipv6=/usr/local/etc/zonemaster/profile-no-ipv6.json
default=/usr/local/etc/zonemaster/profile.json
test=/usr/local/etc/zonemaster/profile-test1.json

[PRIVATE PROFILES]
#test=/usr/local/etc/zonemaster/profile-test1.json
```
```
# zmb --verbose start_domain_test --domain sunet.se --profile test
{"id":1,"method":"start_domain_test","jsonrpc":"2.0","params":{"profile":"test","domain":"sunet.se"}}
{"result":"5d94caf2d74d76f1","id":1,"jsonrpc":"2.0"}
```
Scenario 2:
```
[PUBLIC PROFILES]
default-no-ipv6=/usr/local/etc/zonemaster/profile-no-ipv6.json
default=/usr/local/etc/zonemaster/profile.json
#test=/usr/local/etc/zonemaster/profile-test1.json

[PRIVATE PROFILES]
test=/usr/local/etc/zonemaster/profile-test1.json
```
```
# zmb --verbose start_domain_test --domain sunet.se --profile test
{"params":{"profile":"test","domain":"sunet.se"},"jsonrpc":"2.0","id":1,"method":"start_domain_test"}
{"jsonrpc":"2.0","error":{"code":-32603,"message":"Internal error 009 \n"},"id":1}
```

2021-07-02 16:19 UTC, matsduf commented
It does not seems like RPCAPI supports private profiles. They seems to be meaningless.

2021-07-02 16:46 UTC, matsduf approved these changes

2021-07-05 12:26 UTC, merged

2021-11-17 16:00 UTC, pnax commented
## Testing v2021.2

LGTM