fix shared db handler
zonemaster/zonemaster-backend pull request #859
Opened 2021-09-08 13:14 UTC by blacksponge

## Purpose

Do not reuse initial database connection in child processes.

## Context

After commit https://github.com/zonemaster/zonemaster-backend/commit/dc5b1cdad08fd19dfc0985285f6e0ddaa79508c4 the `TestAgent` class create a database handler on the parent process of the test agent. This handler will then be reuse by the child processes. While it seems that some environment the database object will reconnect to the database because of a failing ping result, in my environment the ping was working correctly. This caused all child processes to share a unique database handler which lead to a number of concurrency error.

Example of such error include (for postgres):

```
2021-09-07T10:46:17Z [84688] WARNING - DBD::Pg::db do warning:  at /home/gbm/workspace/zonemaster/zonemaster-backend/lib/Zonemaster/Backend/DB/PostgreSQL.pm line 131.
2021-09-07T10:46:17Z [84688] ERROR - Test died: fd7d3a2187b0bb86: DBD::Pg::db selectrow_array failed: no statement executing at /home/gbm/workspace/zonemaster/zonemaster-backend/lib/Zonemaster/Backend/DB/PostgreSQL.pm line 138.

2021-09-07T10:46:24Z [84713] WARNING - DBD::Pg::db do failed: synchronisation perdue avec le serveur : a re�u le type de message � 1 �, longueur 909194544 at /home/gbm/workspace/zonemaster/zonemaster-backend/lib/Zonemaster/Backend/DB/PostgreSQL.pm line 131.
2021-09-07T10:46:24Z [84713] ERROR - Test died: bb1d7cec5adea48d: DBD::Pg::db do failed: synchronisation perdue avec le serveur : a re�u le type de message � 1 �,
longueur 909194544 at /home/gbm/workspace/zonemaster/zonemaster-backend/lib/Zonemaster/Backend/DB/PostgreSQL.pm line 131.

2021-09-07T10:57:00Z [86056] ERROR - Test died: 169890693b1d69ea: DBD::Pg::db selectall_hashref failed: Field 'hash_id' does not exist (not one of ) at /home/gbm/workspace/zonemaster/zonemaster-backend/lib/Zonemaster/Backend/DB/PostgreSQL.pm line 231.

2021-09-07T10:56:57Z [86054] WARNING - DBD::Pg::db selectrow_array warning:  at /home/gbm/workspace/zonemaster/zonemaster-backend/lib/Zonemaster/Backend/DB/PostgreSQL.pm line 212.
2021-09-07T10:56:57Z [86054] ERROR - Test died: 7129c73974a3361a: malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "(end of string)") at /home/gbm/workspace/zonemaster/zonemaster-backend/lib/Zonemaster/Backend/DB/PostgreSQL.pm line 213.

2021-09-07T10:56:43Z [85996] ERROR - Test died: 61899d176109b9c3: Can't use string ("1") as a HASH ref while "strict refs" in use at /home/gbm/workspace/zonemaster/zonemaster-backend/lib/Zonemaster/Backend/TestAgent.pm line 83.
```

## Changes

This PR simply close the connection to the database for the database object of the TestAgent thus forcing the a lazy reconnection in the child processes.

## How to test this PR

* Configure backend to use postgresql or mysql
* Create a batch job with  enough domains to test

If there is no error then it is good (in some cases it works correctly without this patch, I haven't found why)

2021-09-08 13:56 UTC, matsduf commented
Have you only seen this problem with Postgresql? Do you see the problem at start-up, or later when you add the batch? Do you only see the problem with batches?

2021-09-08 14:04 UTC, blacksponge commented
I have seen this problem with both Postgresql and Mysql (the error for mysql are: `DBD::mysql::db selectrow_array failed: fetch() without execute()` and `DBD::mysql::db selectrow_array failed: Unknown error`) but not sqlite. The problem does not come from the batch feature but more from executing tests concurrently, they can be started with as a batch or not. The problem has only be seen in the test agent, not the rpcapi, as the database objects are not shared between processes there.

For the record, for postgres, I have done tests with the version 3.7.4, 3.9.0 and 3.15.0 of DBD::Pg, version 11 and 12 of postgres and perl 5.34.

2021-09-08 14:11 UTC, pnax approved these changes

2021-09-13 14:59 UTC, matsduf requested changes
It does not work with SQLite under FreeBSD:

```
2021-09-13T14:51:14Z [5608] NOTICE - Loading config: /usr/local/etc/zonemaster/backend_config.ini
2021-09-13T14:51:14Z [5608] NOTICE - Connecting to database 'DBI:SQLite:dbname=/var/db/zonemaster/db.sqlite'
2021-09-13T14:51:15Z [5608] NOTICE - Connecting to database 'DBI:SQLite:dbname=/var/db/zonemaster/db.sqlite'
2021-09-13T14:51:15Z [5615] NOTICE - Daemon spawned
2021-09-13T14:51:15Z [5615] NOTICE - Connecting to database 'DBI:SQLite:dbname=/var/db/zonemaster/db.sqlite'
2021-09-13T14:51:15Z [5615] NOTICE - Connecting to database 'DBI:SQLite:dbname=/var/db/zonemaster/db.sqlite'
2021-09-13T14:52:49Z [5615] INFO - Test found: 01143e378e134ef2
2021-09-13T14:52:49Z [5713] INFO - Test starting: 01143e378e134ef2
2021-09-13T14:52:49Z [5713] WARNING - DBD::SQLite::db do failed: attempt to prepare on inactive database handle at /usr/local/lib/perl5/site_perl/Zonemaster/Backend/DB/SQLite.pm line 233.
2021-09-13T14:52:49Z [5713] ERROR - Test died: 01143e378e134ef2: DBD::SQLite::db do failed: attempt to prepare on inactive database handle at /usr/local/lib/perl5/site_perl/Zonemaster/Backend/DB/SQLite.pm line 233.
2021-09-13T14:52:50Z [5615] NOTICE - Worker process (pid 5713, testid 01143e378e134ef2): Terminated with exit code 0
2021-09-13T14:53:26Z [5615] INFO - Test found: e1f01642fe750785
2021-09-13T14:53:26Z [5810] INFO - Test starting: e1f01642fe750785
2021-09-13T14:53:26Z [5810] WARNING - DBD::SQLite::db do failed: attempt to prepare on inactive database handle at /usr/local/lib/perl5/site_perl/Zonemaster/Backend/DB/SQLite.pm line 233.
2021-09-13T14:53:26Z [5810] ERROR - Test died: e1f01642fe750785: DBD::SQLite::db do failed: attempt to prepare on inactive database handle at /usr/local/lib/perl5/site_perl/Zonemaster/Backend/DB/SQLite.pm line 233.
2021-09-13T14:53:26Z [5615] NOTICE - Worker process (pid 5810, testid e1f01642fe750785): Terminated with exit code 0
```

If works fine with develop on 86ae65a.

2021-09-20 07:19 UTC, blacksponge commented
> It does not work with SQLite under FreeBSD:

I will investigate that.

2021-09-23 12:59 UTC, blacksponge commented
It should now work correctly with sqlite

2021-09-24 13:50 UTC, matsduf commented
> It should now work correctly with sqlite

It works with SQLite under FreeBSD. I have not been able to verify with MySQL due to bugs somewhere.

2021-09-24 15:02 UTC, matsduf commented
Installation works, but there is an error in the tests:
```
t/test01.t ................ # database: SQLite
# not recording
t/test01.t ................ 1/? # running the agent on test d4850462d52cff97
t/test01.t ................ 13/? # running the agent on test e8014ae447a7a18a
t/test01.t ................ 27/? # [
#   {
#     'creation_time' => '2021-09-24 14:59:37',
#     'id' => 'e8014ae447a7a18a',
#     'overall_result' => 'error'
#   },
#   {
#     'creation_time' => '2021-09-24 14:59:32',
#     'id' => 'd4850462d52cff97',
#     'overall_result' => 'error'
#   }
# ]
    # running the agent on test d4557a8d7d1ffa2f
    # running the agent on test 955d2c1e73db64f2
    # running the agent on test ddef509b14eb5332
t/test01.t ................ 39/? 	(in cleanup) DBI connect('dbname=/tmp/oD8qcMWU2P/zonemaster.sqlite','',...) failed: (no error string) at /usr/home/matsd/.cpanm/work/1632495568.7782/Zonemaster-Backend-6.2.0/blib/lib/Zonemaster/Backend/DB.pm line 231.
	(in cleanup) Can't call method "ping" on an undefined value at /usr/home/matsd/.cpanm/work/1632495568.7782/Zonemaster-Backend-6.2.0/blib/lib/Zonemaster/Backend/DB.pm line 80 during global destruction.
t/test01.t ................ ok    
```
The error message does not come when installing develop branch on 82db5f2.

2021-09-24 15:51 UTC, blacksponge commented
> Installation works, but there is an error in the tests

Should be fixed

2021-09-27 12:48 UTC, mattias-p approved these changes
Looks good do me!

2021-09-27 13:04 UTC, matsduf approved these changes
I see no issues.

2021-09-28 08:53 UTC, merged

2021-11-29 16:48 UTC, blacksponge commented
# Tests release 2021.2

no issue detected