Store times in UTC in database
zonemaster/zonemaster-backend pull request #964
Opened 2022-03-22 17:53 UTC by pnax

## Purpose

With #769 we don't use the database time and pass a time in UTC to the database. I think we were already storing date and times in UTC before. So this is just about making it explicit and use a more suitable data type.

## Context

n/a

## Changes

* Modify data types in database
* Deduplicate some code (since we don't rely on databases time functions anymore)
* TODO: provide an upgrade script to update the database (can cover the N.B. from #769) 

## How to test this PR

TODO

2022-03-25 10:19 UTC, matsduf reviewed
It looks good to me.

2022-03-28 13:54 UTC, pnax commented
* Represent time using ISO 8601
* Add an upgrade script to update database schema

2022-03-28 14:46 UTC, matsduf commented on lib/Zonemaster/Backend/DB.pm
>      return strftime "%Y-%m-%d %H:%M:%S", gmtime( $time );
Should not this be ISO 8601 time format too?

2022-03-28 15:44 UTC, matsduf submitted a review, later dismissed
This looks fine.

2022-03-30 14:25 UTC, mattias-p submitted a review, later dismissed

2022-03-30 14:27 UTC, mattias-p commented
BTW do we consider the change in output format to be a breaking change? It's unspecified in the API documentation.

2022-03-30 14:42 UTC, pnax commented
> BTW do we consider the change in output format to be a breaking change? It's unspecified in the API documentation.

Good point. I would say that the output is more precise now (since it explicitly include a UTC+0 timezone). We could add a note in the Changelog, in case people ([like ourselves](https://github.com/zonemaster/zonemaster-gui/blob/develop/src/app/components/result/result.component.ts#L132)) were parsing it.

2022-03-30 16:20 UTC, pnax commented on share/patch/patch_db_zonemaster_backend_ver_8.2.0.pl
> +    };
good point, I've added transactions.

2022-03-30 16:24 UTC, pnax commented
I've made the following changes in the patch script:
* refactor it to be more concise when dealing with the database engine
* make all database updates in one transaction (and rollback on error)
* remove some unnecessary (and wrong) PostgreSQL request

I also updated the PR description to add a note on a possible breaking change.

2022-03-30 16:47 UTC, mattias-p commented on share/patch/patch_db_zonemaster_backend_ver_8.2.0.pl
> +}
Looks fine!

2022-03-30 16:59 UTC, mattias-p commented
This looks good to me. If it turns out that the date format change doesn't break GUI I'll approve.

If it does break GUI I think we should defer that part until 2022.2 and make GUI accept both formats in 2022.1.

2022-03-30 18:57 UTC, matsduf requested changes
Whenever we see that something in the API is not specified in the API.md then we should update there. Please include an update of API.md.

2022-03-31 09:28 UTC, pnax commented
I've made some tests with the GUI.
* with master, everything works fine
* with current develop ([commit f505954](https://github.com/zonemaster/zonemaster-gui/tree/f505954f4c98d73e5870fc2b15b6130e1f38e548)) the line with the test creation time is not displayed.

So regarding the GUI, there is no breaking change.

Now regarding the API documentation, we currently say:

> "creation_time": A timestamp. The time at which the test was enqueued.

and give such example response:

> "creation_time": "2016-11-15 11:53:13.965982",

I think that the document is not explicit on how the returned timestamp is represented. There is no doubt that this PR introduces a change that was not properly documented. That is in a way the purpose of this PR, make a choice and properly document it.

As I see it there are 2 possibilities:
1. we think this is fine to introduce this change and go on (even if it might result in breaking script that parse the `creation_time` field)
2. we think this is a breaking change, and we should take this carefully by delaying this part of the PR (not the whole PR needs to be delayed I think) and add a note about deprecated time representation in the `creation_time` field.

Personally, I'd go with 1 since it requires a little bit less work on our side, which allows us to move on to something else.

Any thoughts?

2022-03-31 10:30 UTC, mattias-p commented
When I looked again at the API documentation I realized that we do document the [timestamp type](https://github.com/zonemaster/zonemaster-backend/blob/master/docs/API.md#Timestamp). And we use the timestamp type in [get_test_results](https://github.com/zonemaster/zonemaster-backend/blob/master/docs/API.md#result-7) too.

Another possibility is to update the format specification in the API documentation together with how timestamps are returned from both methods together. Perhaps in a separate PR. What do you think about that?

To me this PR has great value just by bringing order to how we store dates in the database.

2022-03-31 11:04 UTC, pnax commented
> When I looked again at the API documentation I realized that we do document the [timestamp type](https://github.com/zonemaster/zonemaster-backend/blob/master/docs/API.md#Timestamp).

Thanks for pointing that out, I missed it.

> Another possibility is to update the format specification in the API documentation together with how timestamps are returned from both methods together. Perhaps in a separate PR. What do you think about that?

This might be better indeed. I'll remove the specific commit and open another PR with it.

2022-03-31 11:30 UTC, pnax commented
So I removed the specific commit introducing the change. This PR should now only be on harmonizing the way we store dates in the database across engines and be specific about the fact that we store the times in UTC.

(I've also edited the description to remove the section about the potential breaking change).

2022-03-31 11:32 UTC, pnax commented
> Whenever we see that something in the API is not specified in the API.md then we should update there. Please include an update of API.md.

@matsduf I think this is not relevant anymore in this PR (will be part of another PR).

2022-03-31 11:49 UTC, matsduf commented
> When I looked again at the API documentation I realized that we do document the [timestamp type](https://github.com/zonemaster/zonemaster-backend/blob/master/docs/API.md#Timestamp). And we use the timestamp type in [get_test_results](https://github.com/zonemaster/zonemaster-backend/blob/master/docs/API.md#result-7) too.

What is missing is the time zone.

2022-03-31 11:50 UTC, matsduf approved these changes
It is fine for me. I approve.

2022-03-31 12:04 UTC, pnax commented
> What is missing is the time zone.

Indeed, I updated the API document.

2022-03-31 12:55 UTC, matsduf approved these changes
It still looks fine for me. I re-approve.

2022-03-31 14:36 UTC, merged

2022-04-08 10:20 UTC, matsduf commented
@pnax, I think we have breaking changes for next release of Zonemaster-Backend. Then next version will be v9.0.0.

2022-04-11 09:49 UTC, pnax commented
> I think we have breaking changes for next release of Zonemaster-Backend.

I think we tried to avoid such breaking changes, what would they be?

2022-04-11 10:00 UTC, matsduf commented
There is no breaking change in the RPC-API, but we require a database update. I am not sure how we have treated that before but I think we have taken database changes as breaking before. "[Versioning and Releases]" says

> Changes in [major] number indicate changes in the outward-facing interface, and it means that users of the interface probably have to do changes to their code, or changes of the usage.

[Versioning and Releases]: https://github.com/zonemaster/zonemaster/blob/master/docs/design/Versions%20and%20Releases.md

2022-04-11 10:34 UTC, pnax commented
Thinking about the "outward-facing interface", shouldn't the bump occur when we remove the field instead as at deprecation time?
If so, maybe https://github.com/zonemaster/zonemaster/pull/1054 could be updated with a note on possible component's version bump at removal time.

TBH I'm not entirely sure when it's best to bump version or not. So if we think such changes result in a major update, go for 9.0.0.

2022-04-11 10:36 UTC, pnax commented
> it means that users of the interface probably have to do changes to their code, or changes of the usage.

Thinking about the usages, I'm also wondering if updating the internals (such as the database) won't affect people with scripts connected to the database directly bypassing the RPC-API. So maybe there is a need to change the major version number. But again I'm not sure.

2022-04-11 11:46 UTC, matsduf commented
> Thinking about the "outward-facing interface", shouldn't the bump occur when we remove the field instead as at deprecation time?

I agree that when the field is removed from the RPC methods, it is a major change.

> If so, maybe [zonemaster/zonemaster#1054](https://github.com/zonemaster/zonemaster/pull/1054) could be updated with a note on possible component's version bump at removal time.

I will do that.
 
> TBH I'm not entirely sure when it's best to bump version or not. So if we think such changes result in a major update, go for 9.0.0.

I will add a discussion to our meeting.

2022-04-13 14:02 UTC, matsduf commented
We have concluded that change in the database schema alone is no reason for a major version update.